### ISSUE TITLE
Additional dependencies for Linux

### ISSUE THREAD

**Issue by bertrik** [opendata-stuttgart/airrohr-firmware-flasher#14]
I ran the firmware flasher under Linux Debian 10.0 bullseye/sid and found I needed at least the following dependencies alongside the ones mentioned in README.md:
* pyqt5-dev-tools

And the following python libs (installed with sudo pip install XXX):
* esptool
* zeroconf

**Comment by Informatic** [comment]
`pyqt5-dev-tools` are mentioned in README right now. `esptool` and `zeroconf` have been in `requirements.txt` all along, maybe the `Pipfile` was kept out of sync for some time?

Regardless, this seems to be solved already, closing.
