### ISSUE TITLE
ESP32 NodeMCU CP2102 "chip_id is not supported for ESP32"

### ISSUE THREAD

**Issue by benjamq** [opendata-stuttgart/airrohr-firmware-flasher#25]
Hey guys,

i tried several times to flash my ESP32 CP2102, but the chip_id will not be written.
Is this board not supported or what am i doing wrong?

Thank you

**Comment by Informatic** [comment]
This is likely. Support for ESP32 was not intended/required during
development, but this should be very easy to introduce.

**Comment by benjamq** [comment]
I would appreciate it.

**Comment by ricki-z** [comment]
If you look in our instructions you won't find any hint that the firmware is supporting the ESP32. This MCU isn't binary compatible to the ESP8266. So why did you think the firmware flashed with that tool would work with the ESP32? Just to get a hint where we need to inform the users about this.

**Comment by benjamq** [comment]
I have copied the name "NodeMCU ESP8266, CPU/WLAN" from the construction manual into Amazon.
The first product looked good and i thought it would be fine.

> AZDelivery ESP32 NodeMCU Module WLAN WiFi Development Board mit CP2102 (Nachfolgermodell zum ESP8266) und gratis eBook!

**Comment by benjamq** [comment]
I have bought the "right" one now.
For me its my first microcontroller, and my knowledge about the differences between ESP32/8266 and CP2102 is low. I thought CP2102 is the important number. And ESP32 is the follow-up of the 8266, so what will go wrong.

I found antoher tutorial:
https://www.teco.kit.edu/wp-content/grand-media/application/Anleitung_Crowdsensor_v085.pdf
they have a flasher for ESP32 and shares the data with you (Luftdaten)?!
So you have to circuit them befor my data reaches your server.

@ricki-z maybe my explanation helps you and the community

**Comment by ricki-z** [comment]
You could try their firmware and flasher. With that the data should be send (also) to our servers.
Using their flashing tool to flash our firmware won't work. Our firmware binaries are only working on ESP8266.
