### ISSUE TITLE
Failed to connect to Espressif device: Timed out waiting for packet header

### ISSUE THREAD

**Issue by martinst1** [opendata-stuttgart/airrohr-firmware-flasher#34]
I get this when I try to upload latest.bin or any other.
When trying to erase: could not open port 'COM4': PermissionError(13, 'Access denied.', None, 5)

Please advice?
I am on win 10, with 64 bit drivers, have another sensor (absolutely the same hardware) and I flashed it with ease.

**Comment by martinst1** [comment]
I figured it out - the sensor was connected do D0 & D1 instead to D1 & D2

**Comment by ricki-z** [comment]
So we can close this issue?
