### ISSUE TITLE
Flasher won't find my ESP8266

### ISSUE THREAD

**Issue by serkonda7** [opendata-stuttgart/airrohr-firmware-flasher#39]
I tried all my USB ports with three different cables. but the flasher keeps telling that no boards are found.
I even tested it on two PCs (Manjaro Linux and Windows 10) but nothing works.

**Comment by ricki-z** [comment]
Can you please post a picture of your ESP8266 here?

**Comment by serkonda7** [comment]
Here you go:
![IMG_20200904_154802.jpg](https://user-images.githubusercontent.com/40118727/92246480-187cf880-eec6-11ea-8ef1-df82760c47ec.jpg)

**Comment by serkonda7** [comment]
The problem was that I used a cable without support for data-transfer.
