### ISSUE TITLE
Problem to detect new sensors

### ISSUE THREAD

**Issue by pjgueno** [opendata-stuttgart/airrohr-firmware-flasher#55]
The problem comes from here:
`    
def on_zeroconf_discovered(self, name, address, info):
       
        """Called on every zeroconf discovered device"""
        
        # if (name.lower().startswith('feinstaubsensor')
        
        #         or name.lower().startswith('nam')
        
        #         or name.lower().startswith('smogomierz')
        
        #         or name.lower().startswith('airrohr')
        
        #         or name.lower().startswith(self.customNameSave)):
        
        item = QtWidgets.QListWidgetItem('{}: {}'.format(address, name.split('.')[0]))
        
        item.setData(ROLE_DEVICE, 'http://{}:{}'.format(address, info.port))
        
        self.discoveryList.addItem(item)`
        
 Feel free to help us.

**Comment by ricki-z** [comment]
Should be solved now. There was a change in the ZeroConf lib that needed to be adepted.
