### ISSUE TITLE
Not Working with sensor.community via HTTPS

### ISSUE THREAD

**Issue by liske310** [opendata-stuttgart/airrohr-firmware-flasher#71]
Today I see my data doesn`t send to sensor.community, but to others APIs (in example: Madavi, OpenSenseMap) works ok. I change from HTTPS to HTTP and now works, but can repair for works with https?

**Comment by capitaenz** [comment]
My sensor 1398229 suddenly no longer sends data to the internet. Is it due to the firmware NRZ-2020-133/DE (Nov 29 2020)?

**Comment by DooMMasteR** [comment]
my sensor is now also not using some APIs anymore...

**Comment by ricki-z** [comment]
There is an firmware update available since yesterday evening. Could you please check that this was loaded and installed?
Version is NRZ-2020-133. Maybe the device needs a power cycle after that.

**Comment by liske310** [comment]
Via HTTP it`s works on firmware NRZ-2024-135/PL (Apr 9 2024) I check now via HTTPS - please take me a ~30minutes

**Comment by liske310** [comment]
I confirm, after update works great :)
